site:
  title: "Omarchy"
  logo_text: "Omarchy"
  description: "Beautiful, Modern &amp; Opinionated Linux by DHH"
  url: "https://omarchy.puvvadi.net"
  author: "KD Puvvadi"
  author_url: "https://puvvadi.net"

releases:
  - version: "3.1.5"
    filename: "omarchy-3.1.5.iso"
    size: "6.41 GiB"
    sha256: "92c417f153a1af112973f5af52104d9dd0442d270b0f241bf91a232dd2b5b8df"
    torrent_file: "/torrents/omarchy-3.1.5.iso.torrent"
    magnet_link: "magnet:?xt=urn:btih:bcec829d0102e4782d98713b41b52eb3e9d64327&dn=omarchy-3.1.5.iso&tr=udp%3A%2F%2Ftracker.puvvadi.net%3A8000%2Fannounce&tr=https%3A%2F%2Ftracker.puvvadi.net%2Fannounce&tr=http%3A%2F%2Ftracker.linuxtracker.org%3A2710%2Fcb49e46146888f33046f528e8e7eea94%2Fannounce"
    release_url: "https://github.com/basecamp/omarchy/releases/tag/v3.1.5"
    release_date: "2025-11-03"
    notes: ""
    latest: true
  
  - version: "3.1.4"
    filename: "omarchy-3.1.4.iso"
    size: "6.31 GiB"
    sha256: "fcb050d2adceded03e90939937be01583f6d95829273fd5e037b1fdf7cc81ab8"
    torrent_file: "/torrents/omarchy-3.1.4.iso.torrent"
    magnet_link: "magnet:?xt=urn:btih:45a5c86987608e3366e7601b518b4f03fb77e9d3&dn=omarchy-3.1.4.iso&xl=6781411328&tr=http%3A%2F%2Ftracker.linuxtracker.org%3A2710%2Fcb49e46146888f33046f528e8e7eea94%2Fannounce&ws=http://tracker.linuxtracker.org"
    release_url: "https://github.com/basecamp/omarchy/releases/tag/v3.1.4"
    release_date: "2025-10-28"
    notes: ""
  
  - version: "3.1.3"
    filename: "omarchy-3.1.3.iso"
    size: "6.29 GiB"
    sha256: "fcb050d2adceded03e90939937be01583f6d95829273fd5e037b1fdf7cc81ab8"
    torrent_file: "/torrents/omarchy-3.1.3.iso.torrent"
    magnet_link: "magnet:?xt=urn:btih:18362c1922677fcfb30791002a43fdb29e147c81&dn=omarchy-3.1.3.iso&tr=http%3A%2F%2Ftracker.linuxtracker.org%3A2710%2Fannounce&tr=udp%3A%2F%2Fttk2.nbaonlineservice.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.srv00.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.healthcareindia.store%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.skillindia.site%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.tryhackx.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.hifitechindia.com%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.linuxtracker.org&tr=udp%3A%2F%2Ftracker.torrust-demo.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.zupix.online%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.linuxtracker.org%3A2710%2Fcb49e46146888f33046f528e8e7eea94%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce&tr=udp%3A%2F%2Fwepzone.net%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.theoks.net%3A6969%2Fannounce&tr=http%3A%2F%2Fthetracker.org%3A80%2Fannounce&tr=http%3A%2F%2Fbttracker.debian.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker2.dler.org%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.qu.ax%3A6969%2Fannounce&tr=udp%3A%2F%2Fexplodie.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.plx.im%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.therarbg.to%3A6969%2Fannounce&tr=udp%3A%2F%2Fudp.tracker.projectk.org%3A23333%2Fannounce"
    release_url: "https://github.com/basecamp/omarchy/releases/tag/v3.1.3"
    release_date: "2025-10-24"
    notes: ""

  - version: "3.1.1"
    filename: "omarchy-3.1.1.iso"
    size: "6.29 GiB"
    sha256: "4D2CDF7B0CFE763E32C98447EBE8ADD891F47AB9D054732369B92FCC6DD1BAA8"
    torrent_file: "/torrents/omarchy-3.1.1.iso.torrent"
    magnet_link: "magnet:?xt=urn:btih:03c45c82a5f072dcead2a88f0a5e5123df33ad4c&dn=omarchy-3.1.1.iso&xl=6755719168&tr=udp%3A%2F%2Ftracker2.dler.org%3A80%2Fannounce&tr=http%3A%2F%2Fthetracker.org%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.tryhackx.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fudp.tracker.projectk.org%3A23333%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.therarbg.to%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.linuxtracker.org%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.torrust-demo.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.healthcareindia.store%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.hifitechindia.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce&tr=udp%3A%2F%2Fexplodie.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fttk2.nbaonlineservice.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.plx.im%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.theoks.net%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.skillindia.site%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.zupix.online%3A6969%2Fannounce&tr=udp%3A%2F%2Fwepzone.net%3A6969%2Fannounce&tr=http%3A%2F%2Fbttracker.debian.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.qu.ax%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.linuxtracker.org&tr=udp%3A%2F%2Ftracker.srv00.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=http%3A%2F%2Ftracker.linuxtracker.org%3A2710%2Fcb49e46146888f33046f528e8e7eea94%2Fannounce"
    release_url: "https://github.com/basecamp/omarchy/releases/tag/v3.1.1"
    release_date: "2025-10-20"
    notes: ""

  - version: "3.1.0"
    filename: "omarchy-3.1.0.iso"
    size: "6.28 GiB"
    sha256: "85B9790E7687CA9E8137C9D2B8C52643686C229CAD1E1AAE353C76EE8F6ABA00"
    torrent_file: "/torrents/omarchy-3.1.0.iso.torrent"
    magnet_link: "magnet:?xt=urn:btih:b1a71a21008f0857de3897692e6a0d017ca568c5&dn=omarchy-3.1.0.iso&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=http%3a%2f%2fthetracker.org%3a80%2fannounce&tr=http%3a%2f%2ftracker.linuxtracker.org%3a2710%2fannounce"
    release_url: "https://github.com/basecamp/omarchy/releases/tag/v3.1.0"
    release_date: "2025-10-19"
    notes: ""
    
  - version: "3.0.2"
    filename: "omarchy-3.0.2.iso"
    size: "6.16 GiB"
    sha256: "8D136A99D74EF534B57356268E5DAD392A124C7E28487FC00330AF9105FC6626"
    torrent_file: "/torrents/omarchy-3.0.2.iso.torrent"
    magnet_link: "magnet:?xt=urn:btih:ceaf5102980ff90fd046f3bddfd2fc5e6785d0aa&dn=omarchy-3.0.2.iso&tr=udp%3A%2F%2Ftracker.tryhackx.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fttk2.nbaonlineservice.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.healthcareindia.store%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.qu.ax%3A6969%2Fannounce&tr=udp%3A%2F%2Fwepzone.net%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.srv00.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.hifitechindia.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fexplodie.org%3A6969%2Fannounce&tr=http%3A%2F%2Fbttracker.debian.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.zupix.online%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.theoks.net%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.skillindia.site%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrust-demo.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.therarbg.to%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker2.dler.org%3A80%2Fannounce&tr=udp%3A%2F%2Fudp.tracker.projectk.org%3A23333%2Fannounce&tr=udp%3A%2F%2Ftracker.plx.im%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.linuxtracker.org"
    release_url: "https://github.com/basecamp/omarchy/releases/tag/v3.0.2"
    release_date: "2025-09-29"
    notes: ""
    
  - version: "3.0.1"
    filename: "omarchy-3.0.1.iso"
    size: "7.03 GiB"
    sha256: "760F9F36F33604E530882A78EE3E2F68222BC9F308721CB2056B6AE4E775DFDA"
    torrent_file: "/torrents/omarchy-3.0.1.iso.torrent"
    magnet_link: "magnet:?xt=urn:btih:a3e1f0209c9081682251ecddc57867172f280f41&dn=omarchy-3.0.1.iso&tr=udp://exodus.desync.com:6969/announce&tr=udp://explodie.org:6969/announce&tr=udp://open.demonii.com:1337/announce&tr=udp://open.stealth.si:80/announce&tr=udp://tracker.healthcareindia.store:1337/announce&tr=udp://tracker.hifitechindia.com:6969/announce&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://tracker.plx.im:6969/announce&tr=udp://tracker.qu.ax:6969/announce&tr=udp://tracker.skillindia.site:6969/announce&tr=udp://tracker.srv00.com:6969/announce&tr=udp://tracker.theoks.net:6969/announce&tr=udp://tracker.therarbg.to:6969/announce&tr=udp://tracker.torrust-demo.com:6969/announce&tr=udp://tracker.tryhackx.org:6969/announce&tr=udp://tracker.zupix.online:6969/announce&tr=udp://tracker2.dler.org:80/announce&tr=udp://ttk2.nbaonlineservice.com:6969/announce&tr=udp://udp.tracker.projectk.org:23333/announce&tr=udp://wepzone.net:6969/announce"
    release_url: "https://github.com/basecamp/omarchy/releases/tag/v3.0.0"
    release_date: "2025-09-18"
    notes: ""
